### ISSUE TITLE
작은 기능들

### ISSUE THREAD

**Issue by jootang2** [jootang2/PROJECT_TIMECAPSULE#17]
# Description

핵심기능이 아닌 작은 기능들 구현

# Todo
- [ ] 공지사항
- [ ] 마이페이지 => 비밀번호 변경 버튼
- [ ] 마이페이지 => 묻은 캡슐 , 작성 중 캡슐, 완료된 캡슐 보이게
- [ ] 캡슐을 열어볼 때 최대 5명한테 보낼 수 있게

# ETC
기타사항
