### ISSUE TITLE
Page Design

### ISSUE THREAD

**Issue by jootang2** [jootang2/PROJECT_TIMECAPSULE#18]
# Description

Page Design

# Todo
- [ ] Main Page
- [ ] 타임캡슐 만드는 페이지
- [ ] 타임캡슐 내부 게시판 페이지
- [ ] 내부 게시판 상세 게시물 페이지
- [ ] 내부게시판 글 쓰는 페이지
- [ ] 타임캡슐 묻는 페이지
- [ ] 작성중인 타임캡슐 페이지
- [ ] 묻혀있는 타임캡슐 페이지
- [ ] 마이페이지
- [ ] 꺼낼 때 페이지

# ETC
기타사항
