### ISSUE TITLE
위치 정보 저장 기능

### ISSUE THREAD

**Issue by jootang2** [jootang2/PROJECT_TIMECAPSULE#20]
# Description

위치 정보 저장 기능

# Todo
- [ ] 마커 여러 개 생성 가능
- [ ] 지우기 클릭 시 지우기 가능
- [ ] 마커에 간단한 정보 저장 가능
- [ ] 상세페이지에서 저장한 위치 정보 보기 기능

# ETC
기타사항
